# The objective is to perform VSTESTV2 with TimeBasedSlicing

trigger:
- master
jobs:
- job: RunTest1
  displayName: 'Run Tests'
  pool: Default
  steps:              
  - task: VisualStudioTestPlatformInstaller@1
    displayName: 'Visual Studio Test Platform Installer'
    inputs:
      versionSelector: 'latestPreRelease'  
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '**\\*TimeBasedSlicingProject*.dll'
      distributionBatchType: 'basedOnExecutionTime'
      searchFolder: '$(System.DefaultWorkingDirectory)\bin\Debug\'
      batchingBasedOnAgentsOption: 'customTimeBatchSize'
      customRunTimePerBatchValue: 65
      vsTestVersion: 'toolsInstaller'
